### ISSUE TITLE
MoE support

### ISSUE THREAD

**Issue by edvardasast** [egorsmkv/NLLB-Translator#3]
Hi, is it possible to add MoE model support?

**Comment by egorsmkv** [comment]
This project uses `transformers`. The [documentation says](https://huggingface.co/docs/transformers/model_doc/nllb) this:

> This implementation contains the dense models available on release. Let us know via a GitHub issue if you would like to see the MoE models as well.

So you can create an issue in theirs repository - https://github.com/huggingface/transformers
